### ISSUE TITLE
Final ready for grading!

### ISSUE THREAD

**Issue by ipowers-matc** [madisoncollege-it-programs/python-scripting-ipowers-matc#17]
I really gave this my best best shot. I think (hope?) I did decent but I'll have to let you be the judge on that!
Sorry again for not staying on top of this class as well as I could have. I was focusing so much on VoIP and Cisco 3 because those classes take an ungodly amount of work. I for sure could have been a little more balanced with my attention to each class, but I'm proud of what I've submitted in the past as well as what I'm submitting today. I also did very well in the other classes I took this semester.

You did an awesome job teaching this semester and I can tell, even though you were a bit rusty at the start, you're going to be a great fit with future students. You really care about the quality of the class which I think is extremely important to a students learning.
Hopefully Jackson and I weren't too distracting in class - at least not all the time ;)  

Hope you have a wonderful holiday break! See you around campus I'm sure! Say hi if you do :)

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208153029-873081b2-643b-455f-b899-e5458a454f01.png)
