### ISSUE TITLE
Week 3 is ready for grading!

### ISSUE THREAD

**Issue by ipowers-matc** [madisoncollege-it-programs/python-scripting-ipowers-matc#3]
I had a little trouble with the repeating of the varBlue. Maybe we can go over this in class on Tuesday? I think I must have just spaced some part of class where we talked about it. Hopefully this is an acceptable method? Didn't seem to be against the rules.

**Comment by cethenmc** [comment]
Isaac - Next time, it may help to download the Word document assignment.  You should have added a question mark at the end of #3.  Technically, in #13, you should have had spaces between every "][" and you should have had the same number of spaces in #13 inside the brackets as there were dollar signs in #12.  Please be more careful in week 4.  I will deduct it in the future.  ~Chris

**Comment by cethenmc** [comment]
cat

**Comment by cethenmc** [comment]
Actually, Isaac, I said in class not to print out Blue 10 times, so I will deduct one point.  You were supposed to make the line as short as possible using techniques we learned in class.  Please reply to this issue when you figure out a more efficient way to do that and have pushed to gitHub for me to regrade.  Thanks!  ~Chris

**Comment by ipowers-matc** [comment]
Updated and pushed

**Comment by cethenmc** [comment]
Much better!  Full credit!
