### ISSUE TITLE
Midterm-slicing.py is ready

### ISSUE THREAD

**Issue by ipowers-matc** [madisoncollege-it-programs/python-scripting-ipowers-matc#8]
Slicing is ready for grading!

**Comment by cethenmc** [comment]
You put a lot of work into this to try to attain the results, more than thinking about what was asked.  Other than missing a period you did pretty well for choosing a complicated path (1 pt).  You tended to avoid the negatives and intermingled with positives.  For the three variables you went positive or intermingled, I am deducting (3 pts).  Finally, the join() which was hinted to you would have helped your case (2 pts).  28/34.
